//OBJETOS NA PROGRAMAÇÃO É UMA FORMA DE REPLICARMOS COISAS DO MUNDO REAL PARA A PROGRAMAÇÃO.

//DECLARAMOS OBJETOS COM let E constantes SEGUIDOS DE {}
//OS OBJETOS POSSUEM PROPIEDADES QUE SÃO chaves e valores
//QUANDO DEFINIMOS UMA CHAVE E VALOR E FORMOS ADICIONAR MAIS, INSERIMOS UMA VIRGULA

//CRIANDO UM OBJETO
let pessoa = {

    'nome': 'Pedro',
    'idade': 23,
    'profissão': 'dev'
}

//ACESSAMOS AS PROPIEDADES DOS OBJETOS DIFERENTE DOS ARRAYS, DESTA VEZ UTILIZAREMOS A NOTAÇÃO ' . '
//nome objeto + . propiedade
console.log(pessoas.nome);

//DA FORMA QUE VIMOS ACIMA, DECLARAMOS APENAS UM OBJETO PESSOA, PARA DECLARAMOS MAIS OBJETOS DEVEMOS 
//MESCLAR COM OS ARRAYS. ANTES DE DECLARARMOS AS {}, ENVOLVEMOS ELAS COM COLCHETES

//CRIANDO UM ARRAY DE OBJETOS
let pessoas = [
    {
        'nome': 'Pedro',
        'idade': 23,
        'profissão': 'dev'
    },

    {
        'nome': 'Manel',
        'idade': 24,
        'profissão': 'design'
    }
]

//QUANDO FORMOS DECLARAR MAIS DE UM OBJETO, DEPOIS DA PRIMEIRA {} INSERIMOS UMA " , ".
//PODEMOS CRIAR OBJETOS COM DIFERENTES TIPOS DE DADOS