//NESSA AULA VAMOS MELHORAR A FORMA DE COMO VEMOS OS OBJETOS E INSERIMOS OS VALORES NELES.

//QUANDO DECLARAMOS OBJETOS COM FORMATO DE FUNÇÕES, ESTMOS PREVIAMENTE ENTRANDO NO CONCEITO DE CLASSES...

//PODEMOS INSERIR FUNÇÕES DENTRO DOS NOSSOS OBJETOS COM ARROW FUNCTIONS.
function Pessoa(){
    this.nome = 'Pedro'
    this.idade = 23
    this.printarNome = ()=>{
        console.log(this.nome);
    }
}

let pessoa = new Pessoa()
pessoa.printarNome()

//VOCÊ PERCEBE QUE NÃO É LEGAL QUANDO CRIAMOS NOVOS OBJETOS E TEMOS QUE MUDAR AS PROPIEDADES EM VEZ DE NÓS MESMOS PASSARMOS OS VALORES?
//VAMOS VER UMA FORMA DE INSERIR OS VALORES NOS NOSSOS OBJETOS NO ATO DE CRIAR. E COMO FAZEMOS ISSO? INSERINDO PARÂMETROS NELES!

function Cachorro(nome, raca ){
    this.nome = nome
    this.raca = raca
}

//NA FORMA ACIMA, ESTAMOS DECLARANDO QUE AS NOSSAS VARIÁVEIS DO OBJETO IRÃO RECEBER POR PARÂMETRO O QUE INSERIRMOS NO ATO DE CRIAÇÃO.
let cachorro = new Cachorro('NEGUINHA', 'PÉ DURO')
console.log(cachorro);

let cachorro_2 = new Cachorro()
console.log(cachorro_2.nome); //AQUI ELE RECEBE undefined POIS NÃO INSERIMOS VALORES NAS VARIAVEIS DO OBJETO
