const arr = ['Pedro', 'Lucas', 'Ribeiro']

//alert(arr[0])

//DESTRUCTURE É QUANDO GUARDAMOS EM UMA VARIÁVEL ESPECIFICA CADA ÍNDICE DE UM ARRAY OU OBJETO

//COMO FAZER:
let [a,b,c] = arr
alert(a)

//A PARTIR DESSE MOMENTO, CONSIGO ACESSAR CADA PROPIEDADE DO ARRAY, PASSANDO UMA VARIAVEL DIFERENTE

