//EM JAVASCRIPT ASSIM COMO EM OUTRAS LINGUAGENS, PODEMOS MANIPULAR AS DATAS

//PARA TRABALHAR COM ELAS TEMOS QUE INSTANCIÁ-LAS:
let date = new Date()

//QUANDO NÃO PASSAMOS NADA DENTRO DO CONSTRUTOR, O JAVASCRIPT ENTENDE QUE ESTAMOS UTILIZANDO A DATA ATUAL.

//MANIPULANDO AS DATAS:
//PEGANDO O DIA DE HOJE
console.log(date.getDate());
console.log(date.getMonth() + 1); //PEGA O MÊS
console.log(date.getDay() + 1); // PEGA O DIA DA SEMANA (SEG, TER...)

//É ADICIONADO O "+ 1", POIS A CONTAGEM DO MÊS E DO DIA DA SEMANA COMEÇA EM 0

