//PODEMOS CRIAR OBJETOS COM FUNÇÕES E UTILIZARMOS ELAS DE UMA FORMA QUE OS PADRÕES ORIENTADO A OBJETOS ACEITA

function Pessoa(){
    this.nome = 'Pedro'
    this.idade = 23
}

let pessoa = new Pessoa()
console.log(pessoa.nome);
console.log(pessoa.idade);

//EXPLICANDO: 
//O new É UMA FORMA DE DECLARAR UM NOVO OBJETO
// A PALAVRA this É UMA PALAVRA RESERVADA QUE SERVE PRA REFERENCIAR UM ATRIBUTO (VARIÁVEL) DE UM OBJETO
//QUANDO CRIAMOS OBJETOS ASSIM, NÃO PODEMOS DEFINIR LET E CONST

//PODEMOS ALTERAR FACILMENTE OS VALORES DOS NOSSOS OBJETOS
pessoa.nome = 'Jakson'
console.log(pessoa.nome);


//PODEMOS CRIAR INFINITOS OBJETOS APENAS CHAMANDO O OBJETO PADRÃO QUE CRIAMOS:
pessoa2 = new Pessoa()
console.log(pessoa2.nome); //AQUI IMPRIME PEDRO, POIS ESTÁ ACESSANDO POR PADRÃO O VALOR DO OBJETO PAI
