//OS LAÇOS DE REPETIÇÃO SERVEM PARA FACILITAR CHAMADAS REPETIDAS DE UM CÓDIGO, POIS EM VEZ DE IRMOS CHAMANDO DE UM POR UM 
//MANUALMENTE, UTILIZAMOS OS LAÇOS PARA FAZER ISSO POR NÓS.

//FOR - É SEMELHANTE AO WHILE, PORÉM SUA VARIÁVEL DE CONTROLE E O INCREMENTO É REALIZADO DENTRO DOS PARAMETROS
//MUITO UTILIZADO PARA MANIPULAÇÃO DE ARRAYS

//DECLARANDO O LAÇO FOR
for(var i =1; i <= 10; i++){
    console.log('Contagem: ' + i);
}


//UTILIZANDO FOR COM FUNÇÕES
function printarConsole(){
    console.log('Print');
}

for (let index = 1; index < 10; index++) {
    printarConsole()
}

//O FOR POR MUITAS VEZES É UMA MELHOR ALTERNATIVA DO QUE O WHILE